### ISSUE TITLE
.pretterignore is ignored

### ISSUE THREAD

**Issue by drfiresign** [raxod502/apheleia#21]
Hi there, very happy with apheleia overall, and I apologize if this isn't really the right spot to make this request / open a discussion about this, but I've found that apheleia doesn't seem to follow along with my .`prettierignore` file in my project (using projectile if that's of relevance). It will adhere to the rules in my `.pretterrc.js` file in the project root, but happily skips over the ignore file. Is there something I am able to do to get it to adhere to that file as well?

Thanks very much, big fan of your many contributions to the Emacs ecosystem as well!

**Comment by raxod502** [comment]
This should be fixed by the latest commit. Let me know what you think.

**Comment by eginhard** [comment]
This actually fails to run prettier because of:
https://github.com/raxod502/apheleia/blob/3be4b486dc09df375fe359e3c5a933c53252a146/apheleia.el#L416

I don't know much elisp, but this works for me:
`(when (or (memq 'file command) (memq 'filepath command))`

**Comment by raxod502** [comment]
Sorry about that, and thanks for the correction!

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
