### ISSUE TITLE
Confusion about use of log buffer

### ISSUE THREAD

**Issue by c02y** [raxod502/apheleia#69]
I received the error `Failed to run rustfmt: exit status 1 (see hidden buffer *apheleia-rustfmt-log*)`.

But I cannot find `*apheleia-rustfmt-log*` buffer.

BTW: `rustfmt` binary is already installed

**Comment by raxod502** [comment]
Hey @c02y, thanks for the report. The log buffer is hidden by default, so you need to type a space into the `switch-to-buffer` interface to see it.

I have pushed d3304b018c4586fbdd49d5277740c50f905beae4 which changes this behavior so that the log buffer is non-hidden by default, and the previous behavior can be obtained using the new `apheleia-hide-log-buffer` user option.

Regarding the Rustfmt issue, I saw the same issue, which was in my case due to Apheleia passing the `--unstable-features` and `--skip-children` flags which were unavailable on my version of Rustfmt. I removed them in the same commit linked above, since I think `--unstable-features` was only needed for `--skip-children`, and `--skip-children` seems like it should not be needed if we are formatting from stdin. However, I could be wrong about that. @adimit and @npajkovsky, can you let me know if the revert breaks https://github.com/raxod502/apheleia/pull/45? And if so, is there a way to prevent the options from breaking stable Rustfmt installations? Mine gives

```
% rustfmt --unstable-features --skip-children --quiet --emit stdout < main.rs >/dev/null
Unrecognized option: 'unstable-features'
```

which is

```
% rustfmt --version                                                                     
rustfmt 1.4.37-stable (59eed8a 2021-11-01)
```

from Ubuntu 21.10.

**Comment by npajkovsky** [comment]
No, you're not wrong and you won't break anything.

**Comment by c02y** [comment]
> But I cannot find `*apheleia-rustfmt-log*` buffer.

What I meant is that I could not find it in buffer list, not just in the Emacs frame, actually no any apheleia related buffer in buffer list.

----------------------
**UPDATE**:
I just updated it to the latest commit.
It works fine, and two extra apheleia buffers `*apheleia-diff-log*` and `*apheleia-rustfmt-log*` are created.

**Comment by c02y** [comment]
**UPDATE**:

it seems when rustfmt fails, I have to open `*apheleia-rustfmt-log*` buffer manually to check what is going wrong, is it able to open split the window and open the buffer automatically when `apheleia-format-buffer` fails?

**Comment by raxod502** [comment]
While it would in principle be possible to make Apheleia pop to the log buffer on error, I question whether that is actually a good idea. Apheleia is typically enabled to run on `after-save-hook`, in an asynchronous manner. This would mean that the current buffer would be switched unexpectedly after a nondeterministic delay, which feels like a bad user experience to me. Is there something about switching to the buffer manually which is inconvenient for you?

You are also correct that the log buffer contains all errors, because it is as the name suggests: a log. The most recent entry is at the bottom. I added a user option `apheleia-hide-old-log-entries` that allows customizing this behavior; please refer to the newly added documentation. In addition, I refactored the other code related to logging that was recently added by @mohkale, to hopefully improve readability. In particular, a timestamp is now included, which should make it impossible to mistake which entry is the most recent. Also, I fixed various bugs related to log buffer management, most concerningly the fact that formatter output was actually inserted at point rather than appended to the end of the buffer.

**Comment by c02y** [comment]
> While it would in principle be possible to make Apheleia pop to the log buffer on error, I question whether that is actually a good idea.

Maybe an option would be better. 
Split the window and open the error buffer, if formatter runs OK, then close it automatically, this is the emacs-format-all's logic, I really like it.

Also, I've tried `apheleia-hide-old-log-entries`, it doesn't hide the old error when formatter runs successfully, I thought the log buffer would be empty if it runs OK.

**Comment by mohkale** [comment]
For what it's worth I agree we shouldn't show the log buffer by default, at least on save if the formatter fails and the buffer is switched I'd probably just find it frustrating. Most of the time I'm using a linter such as pylint which'll probably tell me what the error causing the formatter to fail was. However we could add a hook or another variable users could use to show the log buffer themselves. Something like `apheleia-run-formatter-failed-hook`. Pass it the symbol of the failed formatter and the end-user could probably reconstruct the log buffer-name and display it in a hook.

**Comment by adimit** [comment]
I agree that formatters shouldn't pop up error message buffers by themselves! I found that hugely frustrating with typescript's prettier-mode.

The hook could be a post apheleia run-hook that is run with the status of the last task as an argument. That's more generic than a hook specific to failure and would allow for more user customisation.

**Comment by raxod502** [comment]
> Maybe an option would be better

I have no objection to making it possible, but I don't want to add an out-of-the-box way to enable the functionality unless we can do it in a way that's a good user experience, and I don't see one at present. I don't think having a package change someone's window configuration unexpectedly is a good idea.

> it doesn't hide the old error when formatter runs successfully

That's because no logging happens except on error, so you'd need to customize `apheleia-log-only-errors` to nil.

> The hook could be a post apheleia run-hook that is run with the status of the last task as an argument

Yeah, I agree with that suggestion. Had to do a fair bit of refactoring to get information about the formatter threaded down far enough, but I think the result is an improvement. We now have `apheleia-formatter-exited-hook` which is called on both success and failure for each formatter, with context passed in as keyword arguments. This can be used to implement any UI logic the user desires. In particular it allows implementing `apheleia-hide-old-log-entries` yourself, so I removed that user option, it wasn't that good of an experience anyway in my opinion (it pretends that the log is not a log, but a status buffer, which it isn't -- if we want a status buffer we should implement a status buffer, not hack the log).

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
