### ISSUE TITLE
Race condition when saving multiple buffers in a short time

### ISSUE THREAD

**Issue by raxod502** [raxod502/apheleia#8]
Currently if you save a buffer and then switch to a different buffer before Apheleia can finish reformatting, the contents of the new buffer can get overwritten. We need to save the buffer that was current when `apheleia-format-buffer` was called, and be sure to update that buffer.

**Comment by aaronjensen** [comment]
Just came here to report this. There's a possibly related issue which is that if you save two buffers in quick succession, one of them fails to reformat.

**Comment by axelf4** [comment]
I currently have the issue described by @aaronjensen using Apheleia 1.1.2 (and the formatter [purty]). Have also had the buffer contents be replaced with nothing, again when saving multiple files.

[purty]: https://gitlab.com/joneshf/purty

**Comment by raxod502** [comment]
Yes... I think this is still an issue. In particular, I've reproduced it occasionally when using the `C-x s` "save all buffers" command, and typing `!` to save them all at the same time.

**Comment by dsedivec** [comment]
Could this possibly be because the asynchronous commands might all try to use buffers such as ` *apheleia-patch*` at the same time?  See https://github.com/raxod502/apheleia/blob/f865c165dac606187a66b2b25a57d5099b452120/apheleia.el#L380.

Also, if you happen to have files with the same name in different directories, and you try to format them at the same time, I think this code might have a similar problem: https://github.com/raxod502/apheleia/blob/f865c165dac606187a66b2b25a57d5099b452120/apheleia.el#L271-L274

**Comment by raxod502** [comment]
Oh yeah, that's obviously the problem. Thanks for finding it. Regarding the second code snippet, it's actually even worse than you suggested: `name` there is the name of the formatter, not the name of the file, so there will be a collision for any files of the same type, not just for files that have the same name.

**Comment by mohkale** [comment]
Ok, looks like I rediscovered and opened a new issue for this by accident :smiley:. See #64 and the subsequent PR #65 which should fix it.

**Comment by mohkale** [comment]
This can also be closed now I think.

**Comment by raxod502** [comment]
Awesome, I agree.

**Comment by vincentbernat** [comment]
A release would be much appreciated. It seems 1.2 still has this bug.

**Comment by raxod502** [comment]
https://github.com/raxod502/apheleia/releases/tag/v2.0 :tada:
